const en: { [s: string]: string } = {
    'Account': 'Account',
    'Action': 'Action',
    'Add': 'Add',
    'Added': 'Added',
    'AddDate': 'AddDate',
    'AddTime': 'AddTime',
    'Add Attribute': 'Add Attribute',
    'Add Custom Attribute': 'Add Custom Attribute',
    'Add Filter': 'Add Filter',
    'Adding Elements': 'Adding elements to canvas',
    'Add Related': 'Add Related',
    'Add Rule Hint': 'Press + to add a new Rule/Grp',
    'Add Tags': 'Add Tags',
    'Add Terminus': 'Add Terminus',
    'Add To Canvas': 'Add To Canvas',
    'Advanced Statistics': 'Advanced Statistics',
    'AdvancedStat': 'Advanced',
    'Alignment and Gap': 'Alignment and Gap',
    'All': 'All',
    'All Annotations': 'All Annotations',
    'Ambiguous hint': 'Split keywords by comma',
    'Analyze Case': 'Analyze Case',
    'And': '&',
    'Annotation': 'Annotation',
    'Api Service Not Available': 'Api Service {{service}} not Available',
    'Apply To': 'Apply To',
    'ASTAR': 'ASTAR',
    'Attr Indicator': 'Attr Indicator',
    'Attribute Id Column': 'Id Column',
    'Attribute is required': 'Attribute is required',
    'Attribute Mapping': 'Attribute Mapping',
    'Attribute Name Field': 'Name Column',
    'Attribute name should not contain colon': '{{type}} {{name}} contains attribute with invalid format,note that empty string or colon(:) is not allowed',
    'Attribute Prefix': 'Prefix',
    'Attribute UsePrefix': 'Use Prefix',
    'Attributes': 'Attributes',
    'Attrs': 'Attrs',
    'Align': 'Align',
    'Already exists': 'already exists',
    'Analyze': 'Analyze',
    'Are you sure to delete?': 'Are you sure to delete?',
    'Auto Mapping': 'Auto Mapping',
    'Auto Play Next': 'Auto Play Next',
    'Auto Rotate': 'Auto Rotate',
    'Base': 'Base',
    'Basic Data Dataset': 'Basic Data Dataset',
    'Basic Data Dataset is Required': 'Basic Data Dataset is Required',
    'Basic Info': 'Basic Info',
    'BLOCKQUOTE': 'BLOCKQUOTE',
    'Back': 'Back',
    'Bold': 'Bold',
    'Border Color': 'Border Color',
    'Bowtie Incoming': 'Bowtie Incoming {{suffix}}',
    'Bowtie Indegrees': 'Bowtie Indegrees',
    'Bowtie Outdegrees': 'Bowtie Outdegrees',
    'Bowtie Outgoing': 'Bowtie Outgoing {{suffix}}',
    'BgColor': 'BgColor',
    'Blueprint and Summary': 'Blueprint & Summary',
    'Build Time': 'Build Time',
    'Can only consist of Chinese characters, numbers, letters, and underscores': 'can only consist of Chinese characters, numbers, letters, and underscores',
    'Cannot be empty': 'cannot be empty',
    'Canvas Info': 'Graph Info',
    'Changed': 'Changed',
    'Changed Elements': 'Changed Elements',
    'Clear': 'Clear',
    'Clear All Mappings': 'Clear All Mappings',
    'ClearAll': 'Clear All',
    'Clear Communities': 'All Communities',
    'Clear Canvas': 'All elements',
    'Clear Edge Color': 'Clear Relation Color',
    'Clear Mapping': 'Clear Mapping',
    'Clear Selected': 'Clear Selected',
    'Clear Selected Style': 'Clear Selected Style',
    'Click to choose two entities': 'Click to choose two entities',
    'Close': 'Close',
    'Close Heat': 'Close Heat',
    'Close Map': 'Close Map',
    'Closeness Centrality': 'Closeness Centrality',
    'Cluster': 'Community',
    'Cluster By': 'Community By',
    'Cancel': 'Cancel',
    'Cannot be placed at root level': '{{entityName}} cannot be placed at root',
    'Collapse': 'Collapse',
    'Collapse All Communities': 'Collapse All Communities',
    'Collapsed community warning': 'Collapsed community is supported when activating Time series in the current version, all communities are expanded',
    'Color': 'Color',
    'Cols': 'Cols',
    'Combined Filter': 'Combined Filter',
    'Common Neighbors Only': 'Common Neighbors Only',
    'Community': 'Community',
    'Community By': 'Community By',
    'Community Config': 'Community',
    'Community Discovery': 'Community',
    'Community Exploration': 'Community Exploration',
    'Community Result': 'Community',
    'Community Size': 'Maximum No. of communities',
    'Community Size is required': 'Community Size is required',
    'Company': 'Company',
    'Concept Type': 'Concept Type',
    'Concept Label': 'Concept Label (Label)',
    'Configure heatmap based on entity field': 'Configure heatmap based on entity field',
    'Configure Weight': 'Configure Weight',
    'Configure Style': 'Configure Style',
    'Confirm': 'OK',
    'Confirm Closure': 'Confirm Closure',
    'Connect': 'Connect',
    'Copy': 'Copy',
    'Copy1': 'Copy',
    'Copy As': 'Copy As',
    'Count': 'Count',
    'CPU Number': 'CPU Number',
    'Create Attribute': 'Create Attribute',
    'Create individual analysis': 'Create individual analysis',
    'CreateLink': 'CreateLink',
    'Current': 'Current',
    'Current Canvas': 'Current Canvas',
    'Current Edge Count': 'Relation Count',
    'Current Node Count': 'Entity Count',
    'Current Community Count': 'Community Count',
    'Current Obj': 'Current',
    'Current Layout': 'Current Layout',
    'Current Path': 'Current Path',
    'Current Path Algorithm': 'Current Path Algorithm',
    'Current Path Length': 'Current Path Length',
    'Current ResourcePool': 'Current Resource Pool',
    'Current Tags': 'Current Tags',
    'Current Version': 'Current Version',
    'Custom macro hint': 'e.g. return node.getValue("school").substring(1,3);',
    'Customized Community': 'Community',
    'Customized Range': 'Customized Range',
    'Customized Time Range': 'Customized Time Range',
    'CVAT:Reset': 'Reset',
    'Data Distribution': 'Data Distribution',
    'Dataset ID is Required': 'Dataset ID is Required',
    'Data Type': 'Data Type',
    'Day': 'Day',
    'Decompression Success': 'Decompression Success',
    'Decompression Failed': 'Decompression Failed',
    'Default': 'Default',
    'Default Resource': 'Default Resource Pool',
    'Degree Centrality': 'Degree Centrality',
    'Delete': 'Delete',
    'Delete Attribute': 'Delete Attribute',
    'Delete Community': 'Delete Community',
    'Delete Connection': 'Delete Connection',
    'Delete obj': 'Delete Obj',
    'Delete Terminus': 'Delete Terminus',
    'Delete this vertex': 'Delete this vertex',
    'Delete this edge': 'Delete this Relation',
    'Deleted': 'Deleted',
    'Deleted Edges': 'Deleted Relations',
    'Deleted Entities': 'Deleted Entities',
    'Deletion ramifications': 'Obj cannot be restored, are you sure?',
    'Description': 'Description',
    'Diff Base': 'Diff Base',
    'DIJKSTRA': 'DIJKSTRA',
    'Direction': 'Direction',
    'Dirty flow closure hint': 'Any unsaved data in {{name}} will be lost, are you sure to close it?',
    'Discovery': 'Discovery',
    'Discovery Hint': 'Define community by conceptual categories and attributes',
    'Document': 'Document',
    'Edge': 'Relation',
    'Edge Attr Change': 'Relation Attr Change',
    'Edge color by edge count': 'Relation color by count',
    'Edge Config': 'Relation',
    'Edge Count': 'Relation Count:',
    'Edge Display Setting': 'Relation Display Setting',
    'Edge Font Size': 'Relation Font Size',
    'Edge Style': 'Relation Style',
    'Edge thickness by edge count': 'Relation thickness by Relation count',
    'Edge Type': 'Relation Type',
    'Edge with the same name exists': 'Relation with the same name exists',
    'EdgeCount': 'Count',
    'Edit': 'Edit',
    'Edited': 'Edited',
    'Edit Attribute': 'Edit Attribute',
    'Edit Community': 'Edit Community',
    'End time warning': 'Start time should be before or the same as the end time',
    'Entity': 'Entity',
    'Entities': 'Entity',
    'Entity Annotation': 'Entity Annotation',
    'Entity Attr Change': 'Entity Attr Change',
    'Entity Count': 'Entities',
    'Entity Deletion': 'Entity Deletion',
    'Entity Hint': 'Click right corner button to select entities',
    'Entity Label': 'Entity Label',
    'Entity Name': 'Entity Name',
    'Entity Shape': 'Entity Shape',
    'Entity Size': 'Entity Size',
    'Entity Style': 'Entity Style',
    'Entity Type': 'Entity',
    'Expand': 'Expand',
    'Expand All Communities': 'Expand All Communities',
    'Expand all edge hint': 'Expand all relations with the same name, source and target',
    'Expand Community First': 'Communities {{names}} have(s) been expanded in order to show path',
    'Expand edge': 'Expand relation',
    'Expand edge hint': 'Expand relations with the same name, source and target',
    'Expand Recursively': 'Expand Recursively',
    'Export': 'Export',
    'Export obj': 'Export {{title}}',
    'Exceeded character length limit': 'exceeded character length limit {{maxLen}}',
    'Exit Hint': 'Any unsaved data will be lost, are you sure?',
    'External Network Change': 'External Network Change',
    'FAQ': 'FAQ',
    'Failed copied or moved': 'Failed copied or moved',
    'Failed to layout, please choose other Layout Algorithms': 'Failed to layout, please choose other Layout Algorithms',
    'Failed to start app': 'Failed to start App, please check error log in the console',
    'Failed to render canvas': 'Failed to render canvas',
    'Field': 'Field',
    'Field-based': 'Field-based',
    'Field is not filled in': 'Required fields are empty in the highlighted vertices/links',
    'Field Stats': 'Field Stats',
    'Fields & Indicators': 'Fields & Indicators',
    'File Name': 'Name',
    'Filter': 'Filter',
    'Find Shortest path': 'Shortest path',
    'Find shortest path algorithm': 'Find shortest path algorithm',
    'Fit': 'Fit',
    'Font': 'Font',
    'FontColor': 'FontColor',
    'FontName': 'FontName',
    'FontWeight': 'FontWeight',
    'Forward': 'Forward',
    'Fraud Rank (Transwarp)': 'Fraud Rank (Transwarp)',
    'Full Screen': 'Full Screen',
    'Fullscreen: F11': 'Fullscreen: F11',
    'ge': ' ',
    'Global Node Config': 'Global Entity Config',
    'Global Edge Config': 'Global relation Config',
    'Go Analyzing': 'Go',
    'Graph Computation': 'Graph Computation',
    'Graph Display Setting': 'Display',
    'Graph Results': 'Graph Results',
    'Group By': 'Group By',
    'Group': 'Group',
    'GroupPermissionPrefix': 'Permission ',
    'Group/Members Name': 'Group/Members Name',
    'H1': 'H1',
    'H2': 'H2',
    'H3': 'H3',
    'H4': 'H4',
    'H5': 'H5',
    'H6': 'H6',
    'H7': 'H7',
    'HDFS': 'HDFS',
    'Heat Map': 'Heat Map',
    'Heat Map Setting': 'Heat Map Setting',
    'Heavy Edge Detection': 'Heavy Edge Detection',
    'Hide': 'Hide',
    'Hide Community': 'Hide Community',
    'Highlight Neighbors': 'Highlight Neighbors',
    'Home': 'Start',
    'Hour': 'Hour',
    'Hyperlink-Induced Topic Search': 'Hyperlink-Induced Topic Search',
    'H Align': 'Align Horizontally',
    'H equal margin': 'Equal Horizontal Gap',
    'If Entity': 'If Entity',
    'If Relation': 'If Relation',
    'Image': 'Image',
    'Incoming': 'Incoming',
    'Indegree': 'Indegree',
    'Indegree Hint': 'Indegree indicates the number of head ends adjacent to an entity',
    'Indegree Centrality': 'Indegree Centrality',
    'Industry': 'Industry',
    'Input attribute name': 'Input attribute name',
    'Input attribute value': 'Input attribute value',
    'Input entity/relation name': 'Input entity/relation name',
    'Input new name': 'New Name',
    'Inspect Result': 'Inspect Result',
    'Italic': 'Italic',
    'Indgree': 'Indgree',
    'Indicator': 'Indicator',
    'Input a number': 'Input a number',
    'InsertImage': 'InsertImage',
    'InsertLook': 'InsertLook',
    'InserTable': 'InserTable',
    'InsertHorizontal': 'InsertHorizontal',
    'Inspect': 'Inspect',
    'Instance-free startup, no information yet': 'Instance-free startup, no information yet',
    'Internal Network Change': 'Internal Network Change',
    'Invalid Count': 'Invalid Count',
    'Invert Selection': 'Invert Selection',
    'Isolate Selected': 'Isolate Selected',
    'Items': '{{count}} Items',
    'Item required': 'Item required',
    'JustifyCenter': 'JustifyCenter',
    'JustifyFull': 'JustifyFull',
    'JustifyLeft': 'JustifyLeft',
    'JustifyRight': 'JustifyRight',
    'K Core': 'K Core',
    'Keywords is required': 'Keywords is required',
    'L': 'L',
    'Label': 'Label',
    'Label Propagation': 'Label Propagation',
    'Label Propagation Algorithm': 'Label Propagation Algorithm',
    'Last 1 Week': 'Last 1 Week',
    'Last N Month': 'Last {{count}} Month',
    'Last 1 Year': 'Last 1 Year',
    'Layout': 'Layout',
    'Layout Selected': 'Layout Selected',
    'Layouting Canvas': 'Layout Canavas, this might take a while...',
    'Leaf Entity': 'Leaf Entity',
    'Line': 'Line',
    'Line Color': 'Line Color',
    'Line Opacity': 'Line Opacity',
    'LineRank Betweenness Centrality': 'LineRank、 Betweenness Centrality',
    'Loading': 'Loading',
    'Local Upload': 'Local Upload',
    'Location': 'Location',
    'Log Detail': 'Log Detail',
    'Login required': 'Login info is invalidated,please login again',
    'Logout': 'Logout',
    'Map': 'Map',
    'Mappings are reset as dataset has changed': 'Mappings are reset as dataset has changed',
    'Max': 'Max',
    'Max Hops': 'Max Hops',
    'Mean': 'Mean',
    'Median': 'Median',
    'Members': 'Members',
    'Memory': 'Memory',
    'Meta Info': 'Meta info',
    'Merge': 'Merge',
    'Merge all edge hint': 'Merge all relations with the same name, source and target',
    'Merge edge': 'Merge relations',
    'Merge edge hint': 'Merge relations with the same name, source and target',
    'Merge Entities': 'Merge Entities',
    'Micro Service Not Available': '{{sName}} service is not available, this might affect some part of the whole system',
    'Min': 'Min',
    'Minute': 'Minute',
    'Mode': 'Mode',
    'Model:Add Input Field': 'Add Input Field',
    'Model:Add Output Field': 'Add Output Field',
    'Model:Basic Image': 'Basic Image',
    'Model:Choose Mode': 'Choose Mode',
    'Model:Code Detail': 'Code Detail',
    'Model:Code File': 'Code File',
    'Model:Code File Tip': 'Support for files in .ipynb format, and the kernel should be python2, python3 or R (not pySpark3, spark and sparkR)',
    'Model:Create model version': 'Create version',
    'Model:Corresponding output field': 'Corresponding output field',
    'Model:Interface Setting': 'Interface Setting',
    'Model:Version description': 'Version description',
    'Model:Environment': 'Environment',
    'Model:Experiment does not exist': 'Experiment does not exist, please reselect',
    'Model:Experiment is required': 'Experiment is required',
    'Model:Existing service': 'Existing service',
    'Model:Experiment Flow': 'Experiment Flow',
    'Model:Field Type': 'Field Type',
    'Model:File is required': 'File is required',
    'Model:Gateway': 'gateway model',
    'Model:Gateway Hint': 'For the ipynb file of python3, the user needs to deploy the API interface in the ipynb file by himself and deploy it in multi-threaded mode. Advantages: good performance, fast response.',
    'Model:Name cannot contain white spaces': 'Name cannot contain white spaces',
    'Model:Name Repeat': 'Name Repeat',
    'Model:Nbconvert': 'nbconvert model',
    'Model:Nbconvert Hint': 'It is applicable to the ipynb files of python3 / r two kinds of kernel. It does not need to modify the file logic, automatically extracts the input type to deploy the API service, and automatically creates the test request after the user selects the output parameters. Advantages: convenient operation and friendly use',
    'Model:Must start and end with Chinese and English numerals': 'Must start and end with Chinese and English numerals',
    'Model:NewModelService': 'Create new service',
    'Model:Model Online': 'Model Online',
    'Model:Model Service does not exist': 'Model Service does not exist, please reselect',
    'Model:Model service input parameter settings': 'Model service input parameter settings',
    'Model:Model Type': 'Model Type',
    'Model:Model Upload': 'Model Upload',
    'Model:Only Chinese, upper and lower case letters, numbers, dashes, underscores and decimal points are supported': 'Only Chinese, upper and lower case letters, numbers, dashes, underscores and decimal points are supported',
    'Model:Only supports setting a single model service input': 'Only supports setting a single model service input',
    'Model:Original Field Name': 'Original Field Name',
    'Model:Please Input Name Firstly': 'Please Input Name Firstly',
    'Model:Please Select An Image': 'Please Select An Image',
    'Model:Please Select Experiment Flow': 'Please Select Experiment Flow',
    'Model:Project does not exist': 'Project does not exist, please reselect',
    'Model:Project is required': 'Project is required',
    'Model:Select A Code File': 'Select A Code File',
    'Model:Select a file': 'Select a file',
    'Model:Select Input Field': 'Select Input Field',
    'Model:Select Experiment Flow': 'Select Experiment Flow',
    'Model:Select model service': 'Select model service',
    'Model:Select Output Field': 'Select Output Field',
    'Model:Select Project': 'Select Project',
    'Model:Select the image used by the notebook instance to which the code file belongs': 'Select the image used by the notebook instance to which the code file belongs',
    'Model:Service description': 'Service description',
    'Model:Service is required': 'Service is required',
    'Model:Service name': 'Service name',
    'Model:Service type': 'Service type',
    'Model:Set as Model Service Input': 'Set as Model Service Input',
    'Model:Temporarily unable to resolve, please set the input field by yourself': 'Temporarily unable to resolve, please set the input field by yourself',
    'Model:Thread Count': 'Thread Count',
    'Model:Thread Count Should be Integer': 'Thread Count Should be Integer',
    'Model:Upload': 'Upload',
    'Model:Use GPU': 'Use GPU',
    'Model:Version name': 'Version name',
    'Model:Whether to rely on personal third-party packages': 'Whether to rely on personal third-party packages',
    'Model:Whether to rely on the parent file': 'Whether to rely on the parent file',
    'Month': 'Month',
    'More': 'More',
    'More Settings': 'More Settings',
    'Move': 'Move',
    'MTime': 'Modify Time',
    'Name': 'Name',
    'Name cannot be empty': 'Name cannot be empty',
    'Name exists': 'Attr name {{name}} already exists',
    'Name Collision': 'Duplicate File exists in the target folder: {{failedFileNames}}',
    'Name is required': 'Name is required',
    'Name Reg Rule': 'Must start and end with Chinese and English numerals,Only Chinese, upper and lower case letters, numbers, dashes, underscores and decimal points are supported',
    'Need at least one resource pool': 'Need at least one resource pool',
    'Neighbor': 'Neighbor',
    'Neighbor Error Hint': 'Please choose at least one entity type or one relation',
    'New': 'New',
    'New Community': 'New',
    'New Edges': 'New Eelations',
    'New Entities': 'New Entities',
    'New Folder': 'New_Folder',
    'New Label': 'New Label',
    'New Rule': 'Rule',
    'New Rule Group': 'Rule Grp',
    'Next': 'Next',
    'NextStep': 'Next',
    'NFS': 'NFS',
    'No': 'No',
    'No Community': 'No Community',
    'No communities': 'No communities',
    'No Data': 'No Data',
    'No Description': 'No Description',
    'No Match': 'No Match',
    'No object specified': 'No object specified',
    'No time properties hint': 'Current graph contains no time-related properties',
    'Node Config': 'Entity',
    'Node Category': 'Entity Category',
    'None': 'None',
    'Normal': 'Normal',
    'Note': 'Note',
    'Notebook Resource': 'Notebook Resource',
    'Notebook Resource Config': 'Notebook Resource',
    'Notebook Session Tips': 'This session resource is used for the spark-related kernel in the notebook (including spark, pyspark, and sparkr). When the notebook is opened, it depends on the session resource and the personal notebook resource. When the notebook cannot be opened due to the session resource problem, please switch to the session resource.',
    'Notebook Status': 'Notebook Status',
    'Notebook Instance': 'Notebook Instance',
    'NPM': 'NPM',
    'One Way': 'One Way',
    'Oops, something went wrong': 'Oops, something went wrong',
    'Online:Deploy does not exist': 'Deploy does not exist, please reselect',
    'Online:Is it online': 'Is it online',
    'Online:Sub Model Version does not exist': 'Substitute model version does not exist, please reselect',
    'OrderedList': 'OrderedList',
    'Operation Done': 'Operation Done',
    'Or': '|',
    'Organization': 'Organization',
    'Others': 'Others',
    'Outdegree': 'Outdegree',
    'Outdegree Centrality': 'Outdegree Centrality',
    'Outdegree Hint': 'Outdegree indicates the number of tail ends adjacent to an entity',
    'Outgoing': 'Outgoing',
    'Owner': 'Owner',
    'P': 'P',
    'Page Rank': 'Page Rank',
    'Panel Loading': 'Panel Loading',
    'Parameter': 'Parameter',
    'Path Animation can not be played when some communities are collapsed': 'Path Animation can not be played when some community are collapsed',
    'Paths': '{{count}} Path(s)',
    'Path Discovery': 'Path Discovery',
    'Path does not exist': 'Path does not exist',
    'Path indication': 'Path is indicated by highlighted lines',
    'Path Search': 'Path Search',
    'Path Search Result': 'Path Search Result',
    'Person': 'Person',
    'Percent': 'Percent',
    'Permission denied': 'Permission denied',
    'Pic Url': 'Pic Url',
    'Play Rate': 'Play Rate',
    'Please input group name': 'Please input group name',
    'Please input user name': 'Please input user name',
    'Prefix length': 'Prefix length',
    'Prefix length is required': 'Prefix length is required',
    'Prev': 'Prev',
    'PreviousStep': 'Previous',
    'PrimaryKey conflict': 'PrimaryKey can not mapping, please select another column!',
    'Public': 'Public',
    'Quantity': 'Quantity',
    'Quantiles': 'Quantiles',
    'Quartiles': 'Quartiles',
    'Rectangle: R': 'Rectangle: R',
    'Redo': 'Redo',
    'Refresh': 'Refreh',
    'Refresh Page': 'Refrehs Page',
    'Refreshed successfully': 'Refreshed successfully',
    'Remove': 'Remove',
    'RemoveFormat': 'RemoveFormat',
    'Remove Hint': 'Remove from canvas',
    'Rename': 'Rename',
    'Relation': 'Relation',
    'Relation hint': 'Click right corner button to select relations',
    'Relation Type': 'Relation',
    'Relationship': 'Relationship',
    'Relation Filter': 'Relation Filter',
    'Reset': 'Reset',
    'Resource Pool Not Available': 'Resource Pool {{id}} Not Available',
    'Restart': 'Restart',
    'Reset Selection': 'Reset Selection',
    'Return': 'Return',
    'Right click on Node': 'Right Click on Entity to choose start/end',
    'Rotate Clockwise: Ctrl+R': 'Rotate Clockwise: Ctrl+R',
    'Rotate Counterclockwise: Ctrl+Shift+R': 'Rotate Counterclockwise: Ctrl+Shift+R',
    'Rows': 'Rows',
    'Row*Col': 'Row*Col',
    'Rule not valid': 'Rule {{invalidIndex}} not valid',
    'Save': 'Save',
    'Save as': 'Save as',
    'Save AS Case': 'Save As Case',
    'Saved': 'Saved',
    'Saved successfully': 'Saved successfully',
    'Saving': 'Saving',
    'Search': 'Search {{title}}',
    'Search2': 'Search',
    'Search this folder': 'Search this folder',
    'Second': 'Second',
    'Select': 'Select',
    'SelectAll': 'All',
    'Select All': 'Select All',
    'Select All Neighbors': 'Entities and Relations',
    'Select Attr': 'Select Attr',
    'Select Condition': 'Select Condition',
    'Select Ctrl': 'Select Ctrl',
    'Select Entities': 'Select Entities',
    'Select Fields': 'Select Fields',
    'Select Mode': 'Select Mode',
    'Select Neighboring Nodes': 'Neighboring Entities',
    'Select Neighboring Edges': 'Neighboring Relations',
    'Select one entity': 'Select one entity',
    'Select Precision': 'Select Precision',
    'Select Relation': 'Relation',
    'Select Relations': 'Select Relations',
    'Select sth': 'Select an entity or a relation',
    'Select tag': 'Select tag',
    'Select Time': 'Select Time',
    'Select Time Attributes': 'Time Attributes',
    'Selected': 'Selected',
    'Selected Entities Stats': 'Selected Entities Stats',
    'Selected Entity Count': 'Selected',
    'Selected Edges Stats': 'Selected Relations Stats',
    'Selection': 'Selection',
    'Self Loop': 'Self Loop',
    'Service not found': 'Service not found',
    'Session': 'Session',
    'Session All': 'All',
    'Session Log': 'Session Log',
    'Session Ready': 'Current session is ready',
    'Session Resource': 'Session Resource',
    'Session Status': 'Session Status',
    'Session switch to': 'Session is switched to {{pool}}',
    'Set End': 'Set End',
    'Set Relationship': 'Set Relationship',
    'Set Start': 'Set Start',
    'Share': 'Share',
    'shortest path only?': 'shortest path only?',
    'Show All': 'Show All',
    'Show All Data': 'Show All Data',
    'Show': 'Show',
    'Show Community': 'Show Community',
    'Show Header': 'Show Header',
    'Show Note': 'Show Note',
    'ShowRelatedEntitiesTips': 'Tips: To guarantee efficiency, the maximum number of entities queried limit is 100',
    'Show Tag': 'Show Tag',
    'Snap': 'Snap to grids',
    'Single Relationship Detail': 'Single Relationship Detail',
    'Source': 'Source',
    'Source Folder': 'Source Folder',
    'spark.driver.cores': 'spark.driver.cores',
    'spark.driver.memory': 'spark.driver.memory',
    'spark.executor.cores': 'spark.executor.cores',
    'spark.executor.instances': 'spark.executor.instances',
    'spark.executor.memory': 'spark.executor.memory',
    'Speaker-Listener Label Propagation': 'Speaker-Listener Label Propagation',
    'Src and Dest the same': 'Src and Dest cannot be the same',
    'Star Net': 'Star Net',
    'Start': 'Start',
    'Statistics': 'Statistics',
    'Statistical Field': 'Statistical Field',
    'Statistical Indicator': 'Statistical Indicator',
    'Stats Analysis': 'Stats Analysis',
    'Stats Description': 'Stats Description',
    'Stats Fields': 'Stats Fields:',
    'Stats Indicator': 'Stats Indicator:',
    'Stdev': 'Stdev',
    'Stop': 'Stop',
    'Stop Diff': 'Stop Diff',
    'StrikeThrough': 'StrikeThrough',
    'Strongly Connected Components': 'Strongly Connected Components',
    'Sub': 'Sub',
    'Successfully copied or moved': 'Successfully copied or moved',
    'Style': 'Style',
    'Sum': 'Sum',
    'Summary': 'Summary Map',
    'Sup': 'Sup',
    'Switch to': 'Switch to {{theme}}',
    'Switch Session': 'Switch Session',
    'System initialization': 'System initialization',
    'Tags': 'Tags',
    'Target': 'Target',
    'Target Folder': 'Target Folder',
    'Theme': 'Theme',
    'The current system does not support saving blank folders': 'The current system does not support saving blank folders',
    'The empty folder will be cleared automatically after exiting. Are you sure you want to exit?': 'The empty folder will be cleared automatically after exiting. Are you sure you want to exit?',
    'The length cannot exceed {{maxLength}} characters': 'The length cannot exceed {{maxLength}} characters',
    'Rotated {{angle}} degrees clockwise': 'Rotated {{angle}} degrees clockwise',
    'Then Set Style': 'Then Set Style',
    'Thickness': 'Thickness',
    'Time Series': 'Time Series',
    'Tips': 'Tips',
    'Total-With-Folder': 'Total:{{count}} {{title}}(s)，{{folderCount}} Folder(s)',
    'Total-Without-Folder': 'Total:{{count}} {{title}}(s)',
    'Translucent': 'Translucent',
    'Type': 'Type',
    'Type and create your own tag': 'Type and create your own tag',
    'Type is required': 'Type is required',
    'Bidirectional': 'Bidirectional',
    'Underline': 'Underline',
    'Undo': 'Undo',
    'UnorderedList': 'UnorderedList',
    'Url': 'Url',
    'Use GPU': 'Use GPU',
    'Used': 'Used',
    'User': 'User',
    'Upload Pic': 'Upload Pic',
    'Valid Count': 'Valid Count',
    'Value': 'Value',
    'Version Diff Details': 'Version Diff Details',
    'Version Info': 'Version',
    'Version Number': 'Version Number',
    'View Error Log': 'View Error Log',
    'View Files': 'View Files',
    'View More': 'View More',
    'View Package': 'View Package',
    'View SparkUI': 'View SparkUI',
    'View Unzipped Files': 'View Unzipped Files',
    'Visualized Analysis': 'Visualized Analysis',
    'V Align': 'Align Vertically',
    'V equal margin': 'Equal Vertical Gap',
    'Weakly Connected Components': 'Weakly Connected Components',
    'Week': 'Week',
    'Weight Hint': 'Click the top right button to select fields',
    'Weight Field': 'Weight Field',
    'Widget with the same name exists': 'Widget with the same name exists',
    'XL': 'XL',
    'Year': 'Year',
    'You are deleting': 'You are deleting {{n}} {{title}}(s)',
    'You are exporting': 'You are exporting {{n}} {{title}}(s)/folder(s)',
    'YES': 'YES',
    'Yes': 'Yes',
    'Zoom and Panning': 'Zoom & Panning',
    'Zoom in': 'Zoom In',
    'Zoom out': 'Zoom Out',
    'ZoomShortcut': 'Zoom in: Ctrl+Scrollup, Zoom out: Ctrl+Scrolldown',
    '1st font': '1st font',
    '2st font': '2st font',
    '3st font': '3st font',
    '4st font': '4st font',
    '5st font': '5st font',
    '6st font': '6st font',
    '7st font': '7st font',
    '75 Percentiles': '75 Percentiles',
};
export default en;
