const zh: { [s: string]: string } = {
    'Account': '账号',
    'Action': '操作',
    'Add': '添加',
    'Added': '新增',
    'AddDate': '添加日期',
    'AddTime': '添加时间',
    'Add Attribute': '新增属性',
    'Add Custom Attribute': '新增自定义属性',
    'Add Filter': '添加过滤',
    'Add Related': '添加关联实体',
    'Add Rule Hint': '您还未设置条件规则，请点击"+"按钮设置',
    'Add Tags': '添加标签',
    'Add Terminus': '增加输出端口',
    'Add To Canvas': '在画布显示',
    'Adding Elements': '正在添加元素至画布',
    'Advanced Statistics': '高级统计',
    'AdvancedStats': '高级统计',
    'Alignment and Gap': '对齐与间距',
    'All': '全部',
    'All Annotations': '所有注释',
    'Ambiguous hint': '多个关键词用逗号隔开',
    'Analyze Case': '分析案例',
    'And': '且',
    'Annotation': '注释',
    'API Error not defined': '未定义的API错误',
    'Api Service Not Available': 'Api服务{{service}}无法访问，请检查是否已启用',
    'Apply To': '应用于',
    'ASTAR': 'A* 算法',
    'As a whole': '整体匹配',
    'Attr Indicator': '属性及指标',
    'Attribute Id Column': 'Id列',
    'Attribute is required': '属性未填写',
    'Attribute Mapping': '属性映射',
    'Attribute Name Field': '名字列',
    'Attribute name should not contain colon': '{{type}}{{name}}包含非法格式的属性，注意属性名不能为空或者包含冒号',
    'Attribute Prefix': '前缀',
    'Attribute UsePrefix': '使用前缀',
    'Attributes': '属性',
    'Attrs': '属性',
    'Align': '表格位置',
    'Already exists': '已存在',
    'Analyze': '分析',
    'Are you sure to delete?': '确定要删除？',
    'Auto Mapping': '自动映射',
    'Auto Play Next': '连续播放',
    'Auto Rotate': '界面自动旋转',
    'Back': '后退',
    'Base': '基准',
    'Basic Data Dataset': '基础数据数据集',
    'Basic Data Dataset is Required': '基础数据数据集不能为空',
    'Basic Info': '基本信息',
    'Bold': '加粗',
    'Border Color': '边框颜色',
    'Bowtie Incoming': '蝴蝶结入分{{suffix}}',
    'Bowtie Indegrees': '蝴蝶结入度分',
    'Bowtie Outdegrees': '蝴蝶结出度分',
    'Bowtie Outgoing': '蝴蝶结出分{{suffix}}',
    'BgColor': '背景色',
    'BLOCKQUOTE': '引用',
    'Blueprint and Summary': '蓝图与概览',
    'Build Time': '构建时间',
    'Can only consist of Chinese characters, numbers, letters, and underscores': '只能由汉字、数字、字母、下划线组成',
    'Cannot be empty': '不能为空',
    'Changed': '修改',
    'Changed Elements': '变更元素',
    'Collapse': '收起',
    'Collapse All Communities': '收起所有社群',
    'Collapsed community warning': '当前版本不支持在时间序列功能中展示合并社群，已经将全部社群展开',
    'Clear': '清除',
    'Clear All Mappings': '批量清除映射',
    'ClearAll': '清除全部',
    'Clear Communities': '社群',
    'Clear Canvas': '所有元素',
    'Clear Edge Color': '清除边着色',
    'Clear Mapping': '清除映射',
    'Clear Selected': '清除选中',
    'Clear Selected Style': '清除选中格式',
    'Clear Options': '清空选项',
    'Click to add': '点击添加',
    'Click to choose two entities': '点击选择两个实体',
    'Close': '关闭',
    'Closeness Centrality': '接近中心性',
    'Cancel': '取消',
    'Cannot be placed at root level': '{{entityName}}不能被放置到根目录',
    'Cancel Execute': '终止执行',
    'Canvas Info': '图谱信息',
    'Close Heat': '关闭热力图',
    'Close Map': '关闭地图',
    'Cluster': '社群',
    'Cluster By': '社群分组',
    'Concept Type': '概念类型',
    'Connect': '连接',
    'Color': '按颜色',
    'Cols': '列数',
    'Combined Filter': '组合筛选',
    'Common Neighbors Only': '只选择共同邻居',
    'Community': '社群',
    'Community By': '社群分组依据',
    'Community Config': '社群配置',
    'Community Discovery': '社群发现',
    'Community Exploration': '社群探索',
    'Community Result': '社群结果',
    'Community Size': '最大社群数量',
    'Community Size is required': '社群大小未填写',
    'Company': '公司',
    'Concept Label': '概念标签 (Label)',
    'Configure heatmap based on entity field': '根据实体属性值设置热力图',
    'Configure Weight': '选择权重依据',
    'Configure Style': '格式设置',
    'Confirm': '确认',
    'Confirm Closure': '确认关闭',
    'Copy': '复制',
    'Copy1': '复 制',
    'Copy As': '复制为',
    'Count': '计数',
    'CPU Number': 'CPU核数',
    'Create Attribute': '新增属性',
    'Create individual analysis': '创建个体分析',
    'CreateLink': '添加链接',
    'Current': '当前',
    'Current Canvas': '当前画布',
    'Current Edge Count': '边数量',
    'Current Node Count': '节点数量',
    'Current Community Count': '社群数量',
    'Current Layout': '当前布局',
    'Current Obj': '当前对象',
    'Current Path': '当前路径',
    'Current Path Algorithm': '当前选中路径算法',
    'Current Path Length': '当前路径长度',
    'Current ResourcePool': '当前资源池',
    'Current Tags': '当前标签',
    'Current Version': '当前版本',
    'Custom macro': '自定义宏',
    'Custom macro hint': 'e.g. return node.getValue("someAttribute").substring(1,3);//某个属性的第1-3个字符作为依据分组',
    'Customized Community': '自定义社群',
    'Customized Range': '自定义范围',
    'Customized Time Range': '自定义时间范围',
    'CVAT:Reset': '复位',
    'Data Distribution': '数据分布',
    'Data Set': '数据集',
    'Data Type': '数据类型',
    'Dataset ID': '数据集ID',
    'Dataset ID is Required': '数据集ID不能为空',
    'Day': '日',
    'DARK THEME': '深色主题',
    'Decompression Success': '解压成功',
    'Decompression Failed': '解压失败',
    'Default': '默认',
    'Default Resource': '默认资源池',
    'DEFAULT THEME': '默认主题',
    'Degree Centrality': '度中心性',
    'Delete': '删除',
    'Delete Attribute': '删除属性',
    'Delete Community': '删除社群',
    'Delete Connection': '删除连接',
    'Delete obj': '删除对象',
    'Delete Terminus': '删除输出端口',
    'Delete this vertex': '删除该实体',
    'Delete this edge': '删除该边',
    'Deleted': '删除',
    'Deleted Edges': '关系减少',
    'Deleted Entities': '实体减少',
    'Deletion ramifications': '删除后无法恢复，您确定要删除吗?',
    'Description': '描述',
    'Description length must not exceed 256': '描述不能超过256个字符',
    'Diff Base': '对比基准',
    'DIJKSTRA': 'DIJKSTRA 算法',
    'Direction': '方向',
    'Dirty flow closure hint': '{{name}}中未保存的信息将会丢失，确认关闭?',
    'Discovery': '发现',
    'Discovery Hint': '通过概念类别和属性手动定义社群',
    'Document': '文档',
    'Edge': '边',
    'Edge Attr Change': '关系属性变更',
    'Edge color by edge count': '按数量定义线段颜色',
    'Edge Config': '边设置',
    'Edge Count': '关系数量:',
    'Edge Display Setting': '关系线段调节',
    'Edge Font Size': '关系名字体大小',
    'Edge Name': '关系名称',
    'Edge Style': '关系样式',
    'Edge thickness by edge count': '按数量定义线段粗细',
    'Edge Type': '边类型',
    'EdgeCount': '总数',
    'Edge with the same name exists': '已存在同名关系',
    'Edit': '编辑',
    'Edited': '修改',
    'Edit Attribute': '编辑属性',
    'Edit Community': '编辑社群',
    'Edit Config': '编辑配置',
    'Empty Statement': '清空语句',
    'End time warning': '开始时间应当早于或等于结束时间',
    'Entity': '实体',
    'Entities': '实体',
    'Entity Annotation': '重要实体标注',
    'Entity Attr Change': '实体属性变更',
    'Entity Count': '实体总数',
    'Entity Deletion': '实体减少',
    'Entity Hint': '点击右上角选择关联实体的实体标签',
    'Entity Label': '实体标签',
    'Entity Name': '实体名称',
    'Entity Shape': '实体形状',
    'Entity Size': '实体大小',
    'Entity Style': '实体样式',
    'Entity Type': '实体类型',
    'Exceeded character length limit': '超出字符长度限制 {{maxLen}}',
    'Execute Statement': '执行语句',
    'Execute Failed': '执行失败',
    'Execute Successfully': '执行成功',
    'Execute Result': '执行结果',
    'Executing': '执行中',
    'Exit Hint': '任何未保存的数据将会丢失，确定退出?',
    'Expand': '展开',
    'Expand All Communities': '展开所有社群',
    'Expand all edge hint': '展开所有同类关系',
    'Expand All Paths': '展开所有路径',
    'Expand Community First': '为了更好地现实路径,社群{{names}}已展开',
    'Expand edge': '展开同类关系',
    'Expand edge hint': '展开同类关系',
    'Expand Recursively': '递归展开',
    'Expand Selected Path': '展开选中路径',
    'Export': '导出',
    'Export obj': '导出{{title}}',
    'External Network Change': '外部网络变化',
    'folder(s)': '文件夹',
    'FAQ': '常见答疑',
    'Failed copied or moved': '复制或移动失败',
    'Failed to layout, please choose other Layout Algorithms': '布局失败，请尝试选择其他布局算法',
    'Failed to render canvas': '画布渲染失败',
    'Failed to start app': '启动应用失败，请检查控制台中的错误信息',
    'Field': '字段',
    'Field-based': '属性依据',
    'Field is not filled in': '红色高亮节点/边的必填属性未填写',
    'Field Stats': '属性统计',
    'Fields & Indicators': '统计字段及指标',
    'File Name': '文件名',
    'Filter': '过滤',
    'Filter Condition': '筛选条件',
    'Find Shortest Path': '最短路径',
    'Find shortest path algorithm': '最短路径算法',
    'Fit': '适合屏幕',
    'Fold Filter': '收起筛选',
    'Font': '字体',
    'FontColor': '字体颜色',
    'FontName': '选择字体',
    'FontWeight': '段落格式',
    'Forward': '前进',
    'Fraud Rank (Transwarp)': '欺诈分（星环算法）',
    'Full Screen': '全屏',
    'Fullscreen: F11': '全屏: F11',
    'ge': '个',
    'Getting session information': '正在获取session信息',
    'Global Node Config': '全局节点配置',
    'Global Edge Config': '全局边配置',
    'Go Analyzing': '确认分析',
    'Graph Computation': '图计算',
    'Graph Display Setting': '展示设置',
    'Graph Results': '图谱结果',
    'Group By': '分类',
    'Group': '群组',
    'GroupPermissionPrefix': '权限',
    'Group/Members Name': '组/成员名称',
    'H1': '标题一',
    'H2': '标题二',
    'H3': '标题三',
    'H4': '标题四',
    'H5': '标题五',
    'H6': '标题六',
    'H7': '标题七',
    'HDFS': '集群分布式文件',
    'Heat Map': '热力图',
    'Heat Map Setting': '热力图设置',
    'Heavy Edge Detection': '异常边检测',
    'Hide': '隐藏',
    'Hide Community': '隐藏社群',
    'Highlight Neighbors': '高亮相邻节点',
    'Home': '开始',
    'Hour': '小时',
    'Hyperlink-Induced Topic Search': 'HITS排名',
    'H Align': '水平对齐',
    'H equal margin': '实体水平间距相等',
    'If Entity': '如果实体属性满足以下条件',
    'If Relation': '如果关系属性满足以下条件',
    'Image': '图片',
    'Incoming': '入向',
    'Indegree': '入度',
    'Indegree Hint': '表示图谱上以该实体为终点的关系数量总和',
    'Indegree Centrality': '入度中心性',
    'Index': '序号',
    'Indicator': '指标',
    'Industry': '行业',
    'Input a number': '输入数字',
    'Input attribute name': '输入属性名称',
    'Input attribute value': '输入属性值',
    'Input entity/relation name': '请输入实体/关系名称',
    'Input new name': '输入新名字',
    'Input Dataset Setting': '输入数据集设置',
    'InsertImage': '添加图片',
    'InsertLook': '添加表情',
    'InserTable': '添加表格',
    'InsertHorizontal': '添加水平线',
    'Inspect': '查看',
    'Inspect Result': '查看结果',
    'Instance-free startup, no information yet': '无实例启动，暂无信息',
    'Internal Network Change': '内部网络变化',
    'Invalid Count': '无效值',
    'Invert Selection': '反向选择',
    'Isolate Selected': '仅显示选中数据',
    'Italic': '斜体',
    'Items': '{{count}}项',
    'Item required': '必填',
    'I Know': '知道了',
    'JustifyCenter': '居中',
    'JustifyFull': '文本对齐',
    'JustifyLeft': '左对齐',
    'JustifyRight': '右对齐',
    'Keywords is required': '关键词必填',
    'L': '大',
    'Label': '标签',
    'Label Propagation': 'LPA社区聚类',
    'Label Propagation Algorithm': '标签传播',
    'Last 1 Week': '近一周',
    'Last N Month': '近{{count}}月',
    'Last 1 Year': '近一年',
    'Layout': '布局',
    'Layout Selected': '布局选中元素',
    'Layouting Canvas': '正在重新布局，这可能需要点时间...',
    'Leaf Entity': '叶实体',
    'Line': '线段',
    'Line Color': '线段颜色',
    'Line Opacity': '线段不透明度',
    'LineRank Betweenness Centrality': 'betweenness中心性',
    'Loading': '加载中',
    'Local Upload': '本地上传',
    'Location': '地理位置',
    'Log Detail': '日志详情',
    'Login required': '登录状态失效，请重新登录',
    'Logout': '登出',
    'Keyword matching': '关键词匹配',
    'Key value cannot be empty': 'Key值不能为空',
    'Key value cannot be repeat': 'Key值不能重复',
    'K Core': 'K核心',
    'Map': '地图',
    'Mappings are reset as dataset has changed': '数据集发生改变，映射被重置',
    'Max': '最大值',
    'Max Hops': '最大跳数',
    'Mean': '均值',
    'Median': '中位数',
    'Members': '成员',
    'Memory': '内存',
    'Merge edge': '合并同类关系',
    'Merge all edge hint': '合并所有同类关系',
    'Merge edge hint': '合并同类关系',
    'Merge Entities': '合并实体',
    'Meta Info': '元属性',
    'Metric': '指标',
    'Micro Service Not Available': '{{sName}}微服务配置不完整，部分系统功能可能受影响',
    'Min': '最小值',
    'Minute': '分钟',
    'Mode': '众数',
    'Model:Add Input Field': '添加输入字段',
    'Model:Add Output Field': '添加输出字段',
    'Model:Basic Image': '基础镜像',
    'Model:Choose Mode': '选择方式',
    'Model:Code Detail': '代码详情',
    'Model:Code File': '代码文件',
    'Model:Code File Tip': '支持 .ipynb 格式的文件，且kernel应为python2, python3或R (不能是pySpark3, spark和sparkR)',
    'Model:Create model version': '新建模型版本',
    'Model:Corresponding output field': '对应输出字段名称',
    'Model:Interface Setting': '接口设置',
    'Model:Version description': '版本描述',
    'Model:Environment': '环境变量',
    'Model:Experiment does not exist': '实验未找到，请重新选择',
    'Model:Experiment is required': '实验流程必选',
    'Model:Existing service': '选择已有服务',
    'Model:Experiment Flow': '实验流程',
    'Model:Field Type': '字段类型',
    'Model:File is required': '文件必选',
    'Model:Gateway': 'gateway方式',
    'Model:Gateway Hint': '适用于python3的ipynb文件，需要用户自己在ipynb文件中部署好api接口，多线程方式部署。优点:性能好，响应速度快。',
    'Model:Name cannot contain white spaces': '名称不能包含空格',
    'Model:Name Repeat': '名字重复',
    'Model:Nbconvert': 'nbconvert方式',
    'Model:Nbconvert Hint': '适用于python3/R两种kernel的ipynb文件，无需修改文件逻辑，自动抽取输入类型部署api服务，用户选择输出参数后自动建立测试请求。优点:操作方便、使用友好',
    'Model:NewModelService': '新建服务',
    'Model:Model Online': '模型上线',
    'Model:Model Service does not exist': '模型服务未找到，请重新选择',
    'Model:Model service input parameter settings': 'Model服务参数设置',
    'Model:Model Type': '模型类型',
    'Model:Model Upload': '模型上架',
    'Model:Must start and end with Chinese and English numerals': '必须以中文、英文数字开头和结尾',
    'Model:Only Chinese, upper and lower case letters, numbers, dashes, underscores and decimal points are supported': '仅支持中文、大小写字母、数字、短划线、下划线和小数点',
    'Model:Only supports setting a single model service input': '只支持设置单个模型服务输入',
    'Model:Original Field Name': '原字段名称',
    'Model:Please Input Name Firstly': '请先输入字段名称',
    'Model:Please Select An Image': '请选择镜像',
    'Model:Please Select Experiment Flow': '选择实验流程',
    'Model:Project does not exist': '项目未找到，请重新选择',
    'Model:Project is required': '项目必选',
    'Model:Select A Code File': '选择代码文件',
    'Model:Select a file': '请选择文件',
    'Model:Select Experiment Flow': '选择实验流程',
    'Model:Select Input Field': '选择输入字段',
    'Model:Select model service': '选择模型服务',
    'Model:Select Output Field': '设置输出字段',
    'Model:Select Project': '选择项目',
    'Model:Select the image used by the notebook instance to which the code file belongs': '请选择该代码文件所属notebook实例使用的镜像',
    'Model:Service description': '模型服务描述',
    'Model:Service is required': '服务必选',
    'Model:Service name': '模型服务名称',
    'Model:Service type': '模型服务类型',
    'Model:Set as Model Service Input': '设为模型服务输入',
    'Model:Temporarily unable to resolve, please set the input field by yourself': '暂时无法解析，请自行设置输入字段',
    'Model:Thread Count': '线程数',
    'Model:Thread Count Should be Integer': '线程数必须为整数',
    'Model:Upload': '上架',
    'Model:Use GPU': '使用GPU',
    'Model:Version name': '版本名称',
    'Model:Whether to rely on personal third-party packages': '是否依赖个人第三方包',
    'Model:Whether to rely on the parent file': '是否依赖父文件',
    'Month': '月',
    'More': '更多',
    'More than the maximum number of session connection retries': '超过session连接重试最大次数',
    'More Operations': '更多操作',
    'More Settings': '更多设置',
    'Move': '移动',
    'MTime': '修改时间',
    'Name': '名称',
    'Name cannot be empty': '名称不能为空',
    'Name cannot include whiteSpace': '名称不能包含空格',
    'Name Collision': '目标文件夹中存在同名文件: {{failedFileNames}}',
    'Name exists': '属性名{{name}}已存在',
    'Name is required': '名称为必填项',
    'Name length must not exceed 56': '名称不能超过56个字符',
    'Name Reg Rule': '仅支持中文、大小写字母、数字、短划线、下划线和小数点，必须以中文、英文或数字开头和结尾',
    'Need at least one resource pool': '至少需要一个资源池',
    'Neighbor': '邻居',
    'Neighbor Error Hint': '请至少选择一个实体或者一种关系',
    'Network Error': '网络错误',
    'New': '新增',
    'New Community': '新建社群',
    'New Edges': '关系增加',
    'New Entities': '实体增加',
    'New Folder': '新建文件夹',
    'New Label': '创建新标签',
    'New Rule': '新增规则',
    'New Rule Group': '新增规则组',
    'Next': '下一条',
    'NextStep': '下一步',
    'NFS': '网络文件系统',
    'No': '否',
    'No Community': '无社群',
    'No communities': '无社群',
    'No Data': '没有数据',
    'No Description': '没有描述',
    'No Matched': '没有匹配',
    'No object specified': '没有选中对象',
    'No time properties hint': '当前图谱没有时间属性',
    'Normal': '正常',
    'Node Config': '节点配置',
    'Node Category': '节点类型',
    'None': '空',
    'Note': '笔记',
    'Notebook Resource': 'Notebook资源',
    'Notebook Resource Config': 'Notebook资源配置',
    'Notebook Session Tips': '此会话资源用于notebook中spark相关的kernel(包括spark, pyspark和sparkr)，Notebook开启时依赖会话资源和个人Notebook资源，当因会话资源问题造成Notebook无法开启时，请至会话资源处进行资源切换。',
    'Notebook Status': 'Notebook状态',
    'Notebook Instance': 'Notebook 实例',
    'NPM': 'Notebook包',
    'OK': '确定',
    'One Way': '单向',
    'Oops, something went wrong': '页面出错了',
    'Online:Deploy name': '部署名称',
    'Online:Deploy does not exist': '部署未找到，请重新选择',
    'Online:Deploy name is required': '部署名称必填',
    'Online:Full Url': '完整Url',
    'Online:Is it online': '是否上线',
    'Online:Online Type': '上线方式',
    'Online:Replicas': '实例数量',
    'Online:Rollup Upgrade': '滚动升级',
    'Online:Running Envs': '运行时环境变量',
    'Online:Sub Model Version': '替代模型版本',
    'Online:Sub Model Version does not exist': '替代模型版本未找到，请重新选择',
    'Online:Sub Model Version is required': '替代模型版本必选',
    'Online:Url Prefix': 'Url前缀',
    'Operation Done': '操作完成',
    'OrderedList': '有序列表',
    'Or': '或',
    'Organization': '机构',
    'Origin Field DataType': '字段数据类型',
    'Origin Field Description': '字段描述',
    'Origin Field Name': '原字段名称',
    'Others': '其他',
    'Outdegree': '出度',
    'Outdegree Centrality': '出度中心性',
    'Outdegree Hint': '表示图谱上以该实体为起点的关系数量总和',
    'Outgoing': '出向',
    'Owner': '拥有者',
    'P': '正文',
    'Panel Loading': '面板加载中',
    'Paths': '{{count}}条路径',
    'Path Discovery': '路径发现',
    'Path Search': '路径查找',
    'Path Search Result': '路径查找结果',
    'Person': '人',
    'Percent': '百分比',
    'Pic Url': '图片路径',
    'Page Rank': '节点网络排名',
    'Parameter': '参数',
    'Path Animation can not be played when some communities are collapsed': '当前图中存在合并的社群，无法播放路径动画',
    'Path does not exist': '路径不存在',
    'Path indication': '路径已高亮展示',
    'Permission denied': '权限不足',
    'Play Rate': '播放倍数',
    'Please input group name': '请输入群组名',
    'Please input user name': '请输入用户名',
    'Please Input Keywords': '请输入关键字',
    'Please select a dataset as input': '请选择数据集作为输入项',
    'Please Select Data Connection': '请选择数据连接',
    'Prefix length': '前缀长度',
    'Prefix length is required': '前缀长度未填写',
    'Prefix matching': '前缀匹配',
    'Prev': '上一条',
    'PreviousStep': '上一步',
    'PrimaryKey conflict': '主键不能参与映射， 请生新选择!',
    'Public': '公共',
    'Quantity': '数量',
    'Quantiles': '四分位距',
    'Quartiles': '25分位',
    'Rectangle: R': '矩形： R',
    'Redo': '重做',
    'Redo: Ctrl+Y': '恢复： Ctrl+Y',
    'Refresh': '刷新',
    'Refresh Page': '刷新页面',
    'Refreshed successfully': '刷新成功',
    'Relation': '关系',
    'Relation Type': '关系类型',
    'Relation Hint': '点击右上角选择关联实体的关系标签',
    'Relationship': '关系',
    'Relation Filter': '关系过滤',
    'Remove': '移除',
    'RemoveFormat': '清除格式',
    'Remove as Api Service Input': '取消设为API服务输入',
    'Remove Hint': '从画布中移除',
    'Remove Selected': '移除',
    'Rename': '重命名',
    'Request Timeout': '请求超时',
    'Reset Selection': '重置选择',
    'Reset': '重置',
    'Resource Pool Not Available': '资源池 {{id}} 无法访问，请重新选择',
    'Restart': '重启',
    'Return': '返回',
    'Right click on Node': '右击节点选择起/终点',
    'Rotate Clockwise: Ctrl+R': '顺时针旋转: Ctrl+R',
    'Rotate Counterclockwise: Ctrl+Shift+R': '逆时针旋转: Ctrl+Shift+R',
    'Rows': '行数',
    'Row*Col': '设置行列',
    'Rule not valid': '第{{invalidIndex}}条规则配置不完整',
    'Save': '保存',
    'Save as': '另存为',
    'Save As Case': '另存为案例',
    'Saved': '保存成功',
    'Saved successfully': '保存成功',
    'Saving': '保存中',
    'Search': '搜索{{title}}',
    'Search2': '搜索',
    'Search this folder': '搜索当前文件夹',
    'Search All': '查找全部',
    'Search Content': '查找内容',
    'Search Next': '查找下一处',
    'Search Pre': '查找上一处',
    'Search Result': '查询结果',
    'Search Statement': '查找语句',
    'Second': '秒',
    'Select': '选中',
    'SelectAll': '全选',
    'Select All': '全选',
    'Select All Neighbors': '实体和关系',
    'Select Attr': '选择属性',
    'Select Condition': '选择条件',
    'Select Ctrl': '选择控制',
    'Select Entities': '选择实体',
    'Select Fields': '选择属性',
    'Select Mode': '选择方式',
    'Select Neighboring Nodes': '相连实体',
    'Select Neighboring Edges': '相连关系',
    'Select one entity': '选择一个实体',
    'Select Precision': '选择统计精度',
    'Select Relation': '关系',
    'Select Relations': '选择关系',
    'Select sth': '请选择一条边或一个节点',
    'Select tag': '选择标签',
    'Select Time Attributes': '选择时间属性',
    'Selected': '已选',
    'Selected Entities Stats': '选中实体统计',
    'Selected Entity Count': '选中实体数',
    'Selected Edges Stats': '选中关系统计',
    'Selection': '选择',
    'Self Loop': '自环',
    'Service not found': '服务未找到',
    'Session': '会话',
    'Session All': '总',
    'Session Log': '会话日志',
    'Session Ready': '当前会话已准备完成',
    'Session Resource': '会话资源',
    'Session Status': '会话状态',
    'Session switch to': '会话切换到 {{pool}}',
    'Set End': '设置终点',
    'Set Relationship': '设置关系',
    'Set Start': '设置起点',
    'Set as Api Service Input': '设为API服务输入',
    'Server is down': '服务器故障',
    'Share': '分享',
    'shortest path only?': '是否只显示最短路径',
    'Show': '显示',
    'Show All': '显示全部',
    'Show All Data': '显示所有数据',
    'Show Community': '显示社群',
    'Show Detail': '显示详情',
    'Show Header': '显示表头',
    'ShowRelatedEntitiesTips': '提示: 为保证查询效率，限定查询最大关联实数量为100',
    'Snap': '对齐到网格',
    'Single Relationship Detail': '单个关系详情',
    'Source': '起始',
    'Source Folder': '源目录',
    'spark.driver.cores': '驱动器核数',
    'spark.driver.memory': '驱动器内存',
    'spark.executor.cores': '执行器核数',
    'spark.executor.instances': '执行器个数',
    'spark.executor.memory': '执行器内存',
    'Speaker-Listener Label Propagation': 'SLPA社区聚类',
    'Src and Dest the same': '该目录下存在同名，请重命名',
    'Star Net': '星型网络',
    'Start': '启动',
    'Statistics': '统计值',
    'Statistical Field': '统计字段',
    'Statistical Indicator': '统计指标',
    'Stats Analysis': '统计分析',
    'Stats Description': '描述统计',
    'Stats Fields': '统计字段',
    'Stats Indicator': '统计指标:',
    'Stdev': '标准差',
    'Stop': '停止',
    'Stop Diff': '结束对比',
    'StrikeThrough': '删除线',
    'Strongly Connected Components': '强连通子图',
    'Style': '样式',
    'Sub': '下标',
    'Successful copy': '复制成功',
    'Successfully copied or moved': '复制或移动成功',
    'Suffix matching': '后缀匹配',
    'Sup': '上标',
    'Sum': '总和',
    'Summary': '概览地图',
    'Switch to': '切换到{{theme}}',
    'Switch Session': '切换环境',
    'System Id': '系统ID',
    'System Name': '名称',
    'System initialization': '系统初始化',
    'Table Sheet': '明细表',
    'Tag': '标签',
    'Tags': '标签',
    'Target': '目标',
    'Target Folder': '目标文件夹',
    'Theme': '主题',
    'The current system does not support saving blank folders': '当前系统不支持保存空白文件夹',
    'The empty folder will be cleared automatically after exiting. Are you sure you want to exit?': '退出后将自动清除该空文件夹，确定退出吗？',
    'The length cannot exceed {{maxLength}} characters': '长度不能超过{{maxLength}}字符',
    'Rotated {{angle}} degrees clockwise': '已顺时针旋转了{{angle}}度',
    'Then Set Style': '那么设置样式',
    'Thickness': '按粗细',
    'Time Series': '时间序列',
    'Tips': '提示',
    'Token expired': '登录失效',
    'Total-With-Folder': '统计: {{count}}个{{title}}，{{folderCount}}个文件夹',
    'Total-Without-Folder': '统计: {{count}}个{{title}}',
    'Translucent': '半透明',
    'Type': '类型',
    'Type and create your own tag': '输入创建',
    'Type is required': '类型必填',
    'Bidirectional': '双向',
    'Url': '链接地址',
    'Upload Pic': '上传图片',
    'Underline': '下划线',
    'Undo': '撤销',
    'Undo: Ctrl+Z': '撤销： Ctrl+Z',
    'Unfold Filter': '展开筛选',
    'UnorderedList': '无序列表',
    'Use GPU': '使用GPU',
    'Used': '已用',
    'User': '用户',
    'Valid Count': '有效值',
    'Value': '值',
    'Value value cannot be empty': 'Value值不能为空',
    'Version Diff Details': '版本对比详情',
    'Version Info': '版本信息',
    'Version Number': '版本号',
    'View Error Log': '查看报错日志',
    'View Files': '查看文件',
    'View More': '查看更多',
    'View Package': '查看压缩包',
    'View SparkUI': '查看SparkUI',
    'View Unzipped Files': '查看解压文件',
    'Visualized Analysis': '可视化分析',
    'V Align': '垂直对齐',
    'V equal margin': '实体垂直间距相等',
    'Weakly Connected Components': '弱连通子图',
    'Week': '周',
    'Weight Hint': '点击右上角选择最短路径的权重依据',
    'Weight Field': '权重域',
    'Widget with the same name exists': '已存在同名算子',
    'XL': '超大',
    'You are deleting': '将要删除{{n}}个{{title}}',
    'You are exporting': '将导出{{n}}个{{title}}/文件夹',
    'Year': '年',
    'YES': '是',
    'Yes': '是',
    'Zooming and Panning': '缩放和平移',
    'Zoom in': '放大',
    'Zoom out': '缩小',
    'ZoomShortcut': '放大: Ctrl+滚轮上; 缩小: Ctrl+滚轮下',
    'Select Time': '选择时间',
    '1st font': '1号字体',
    '2st font': '2号字体',
    '3st font': '3号字体',
    '4st font': '4号字体',
    '5st font': '5号字体',
    '6st font': '6号字体',
    '7st font': '7号字体',
    '75 Percentiles': '75分位',
    '': '',
    '{{count}} matches': '共 {{count}} 处匹配',
};
export default zh;
